/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  //这里是docs侧边栏的设置
  /*
    intro - intro.md
    下面的category则是创建了一个集合存放一系列文件
  */
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'HTML项目',
      items: ['html/maze', 'html/ball', 'html/art', 'html/gal'],
    }
  ],
};


export default sidebars;
